THREAD_SETTINGS = "settings"
THREAD_TRAY = "tray"
THREAD_PROCESS_LIST_DATA = "process_list_data"
THREAD_PROCESS_LIST_ICONS = "process_list_icons"
THREAD_PROCESS_LIST_OPEN_SERVICE_PROPERTIES = "process_list_open_service_properties"
